import { useState, useEffect } from 'react';
import { Play, Pause, Volume2, Maximize, Film, Clock, Star } from 'lucide-react';
import '@/styles/water-animations.css';

interface InteractiveVideo {
  id: string;
  title: string;
  description: string;
  duration: string;
  technologies: string[];
  features: string[];
  thumbnailUrl?: string;
}

export const InteractiveVideo: React.FC = () => {
  const [selectedVideo, setSelectedVideo] = useState<string | null>(null);
  const [isPlaying, setIsPlaying] = useState(false);
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  const interactiveVideos: InteractiveVideo[] = [
    {
      id: '1',
      title: 'Undersea World',
      description: 'A video created entirely with AI for an immersive 3D exhibition installation, showcasing the diverse ecosystems of the underwater world.',
      duration: '8:45',
      technologies: ['Midjourney', 'Photoshop', 'Premiere', 'GPT-3'],
      features: [ '3D visualization', 'Educational content','Generated by AI']
    },
    {
      id: '2',
      title: 'Zhu Rong And Qing Xian',
      description: 'An AI-powered immersive video that teaches geology through ancient mythology, featuring Zhu Rong, the god of fire, and Qingxian, the goddess of nature, as its main characters.',
      duration: '12:30',
      technologies: ['Midjourney', 'Photoshop', 'Premiere', 'GPT-3'],
      features: ['3D visualization', 'Educational content', 'Generated by AI']
    }
  ];

  return (
    <div className="space-y-8">
      {/* 头部标题 */}
      <div className={`text-center mb-8 ${
        mounted ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'
      } smooth-transition-slow`}>
        <h2 className="text-4xl font-bold gradient-text mb-4">Videos</h2>
        <p className="text-gray-600 text-lg">Visual experiences showcasing creative projects and designs</p>
      </div>

      {/* 特色视频播放器 */}
      {selectedVideo && (
        <div className={`glass-effect rounded-2xl p-6 soft-shadow-lg smooth-transition ${
          mounted ? 'opacity-100 scale-100' : 'opacity-0 scale-95'
        }`}
        style={{
          animationDelay: '0.3s',
          animation: mounted ? 'slide-in-up 0.6s ease-out 0.3s both' : 'none'
        }}>
          <div className="aspect-video bg-gradient-to-br from-slate-100 to-white rounded-2xl relative overflow-hidden shadow-inner">
            <div className="absolute inset-0 flex items-center justify-center">
              <div className="text-center">
                <div className="w-24 h-24 bg-gradient-to-br from-blue-500 to-purple-600 rounded-full flex items-center justify-center mx-auto mb-6 shadow-xl hover-lift smooth-transition">
                  <Play className="w-12 h-12 text-white ml-1" />
                </div>
                <p className="text-gray-800 font-semibold text-lg mb-2">Now Playing</p>
                <p className="text-gray-600">
                  {interactiveVideos.find(v => v.id === selectedVideo)?.title}
                </p>
              </div>
            </div>

            {/* 视频控制覆盖层 */}
            <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/60 to-transparent p-6">
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center space-x-4">
                  <button
                    className="w-10 h-10 bg-white/20 backdrop-blur-sm rounded-full flex items-center justify-center text-white hover:bg-white/30 smooth-transition"
                    onClick={() => setIsPlaying(!isPlaying)}
                  >
                    {isPlaying ? <Pause className="w-5 h-5" /> : <Play className="w-5 h-5 ml-0.5" />}
                  </button>
                  <button className="w-10 h-10 bg-white/20 backdrop-blur-sm rounded-full flex items-center justify-center text-white hover:bg-white/30 smooth-transition">
                    <Volume2 className="w-5 h-5" />
                  </button>
                </div>
                <button className="w-10 h-10 bg-white/20 backdrop-blur-sm rounded-full flex items-center justify-center text-white hover:bg-white/30 smooth-transition">
                  <Maximize className="w-5 h-5" />
                </button>
              </div>

              {/* 进度条 */}
              <div className="bg-white/20 rounded-full h-2 overflow-hidden">
                <div className="h-full w-1/3 bg-gradient-to-r from-blue-500 to-purple-600 rounded-full smooth-transition" />
              </div>
            </div>
          </div>

          <div className="mt-6">
            <h3 className="text-2xl font-bold text-gray-800 mb-3">
              {interactiveVideos.find(v => v.id === selectedVideo)?.title}
            </h3>
            <p className="text-gray-600 mb-4 leading-relaxed">
              {interactiveVideos.find(v => v.id === selectedVideo)?.description}
            </p>
            <div className="flex flex-wrap gap-2">
              {interactiveVideos.find(v => v.id === selectedVideo)?.technologies.map((tech, index) => (
                <span
                  key={index}
                  className="px-3 py-1 bg-gradient-to-r from-blue-100 to-purple-100 text-gray-700 rounded-full text-sm font-medium"
                >
                  {tech}
                </span>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* 视频网格 */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {interactiveVideos.map((video, index) => (
          <div
            key={video.id}
            className={`glass-effect rounded-2xl overflow-hidden hover-lift soft-shadow ripple-effect cursor-pointer smooth-transition ${
              mounted ? 'opacity-100' : 'opacity-0'
            } ${selectedVideo === video.id ? 'ring-2 ring-blue-500/50' : ''}`}
            style={{
              animationDelay: mounted ? `${0.4 + index * 0.08}s` : '0s',
              animation: mounted ? `slide-in-up 0.6s ease-out ${0.4 + index * 0.08}s both` : 'none'
            }}
            onClick={() => setSelectedVideo(video.id)}
          >
            {/* 视频缩略图 */}
            <div className="aspect-video bg-gradient-to-br from-slate-100 to-white relative overflow-hidden group">
              <div className="absolute inset-0 flex items-center justify-center">
                <div className="text-center">
                  <div className="w-16 h-16 bg-gradient-to-br from-blue-100 to-cyan-100 rounded-full flex items-center justify-center mx-auto mb-3 group-hover:scale-110 smooth-transition">
                    <Film className="w-8 h-8 bg-gradient-to-br from-blue-500 to-cyan-500 bg-clip-text text-transparent" />
                  </div>
                </div>
              </div>

              {/* 时长标记 */}
              <div className="absolute bottom-3 right-3 bg-black/60 backdrop-blur-sm px-2 py-1 rounded-lg text-xs text-white font-medium">
                {video.duration}
              </div>

              {/* 悬停覆盖层 */}
              <div className="absolute inset-0 bg-gradient-to-br from-blue-500/10 to-purple-600/10 opacity-0 group-hover:opacity-100 smooth-transition flex items-center justify-center">
                <div className="w-16 h-16 bg-white/90 backdrop-blur-sm rounded-full flex items-center justify-center shadow-xl group-hover:scale-110 smooth-transition">
                  <Play className="w-8 h-8 text-gray-800 ml-1" />
                </div>
              </div>
            </div>

            <div className="p-4">
              {/* 视频信息 */}
              <h3 className="text-lg font-bold text-gray-800 mb-2">{video.title}</h3>
              <p className="text-gray-600 text-sm mb-3 line-clamp-2 leading-relaxed">{video.description}</p>

              {/* 视频时长信息 */}
              <div className="flex items-center text-sm text-gray-500 mb-3">
                <Clock className="w-4 h-4 mr-1" />
                <span>{video.duration}</span>
              </div>

              {/* 技术标签 */}
              <div className="flex flex-wrap gap-1 mb-3">
                {video.technologies.slice(0, 3).map((tech, techIndex) => (
                  <span
                    key={techIndex}
                    className="px-2 py-1 bg-gray-100 text-gray-600 rounded text-xs font-medium"
                  >
                    {tech}
                  </span>
                ))}
                {video.technologies.length > 3 && (
                  <span className="px-2 py-1 bg-gray-100 text-gray-600 rounded text-xs font-medium">
                    +{video.technologies.length - 3}
                  </span>
                )}
              </div>

              {/* 特性 */}
              <div className="text-xs text-gray-500">
                {video.features.slice(0, 2).join(' • ')}
                {video.features.length > 2 && ` • +${video.features.length - 2} more`}
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* 统计信息 */}
      <div className={`glass-effect rounded-2xl p-8 text-center soft-shadow smooth-transition ${
        mounted ? 'opacity-100' : 'opacity-0'
      }`}
      style={{
        animationDelay: mounted ? '1.0s' : '0s',
        animation: mounted ? 'slide-in-up 0.6s ease-out 1.0s both' : 'none'
      }}>
        <h3 className="text-2xl font-bold gradient-text mb-6">Video Analytics</h3>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
          {[
            { number: '12:24', label: 'Avg. Duration', icon: Clock, color: 'from-purple-400 to-pink-500' },
            { number: '4.8', label: 'Quality Rating', icon: Star, color: 'from-yellow-400 to-orange-500' }
          ].map((stat) => (
            <div key={stat.label} className="text-center">
              <div className={`inline-flex p-4 rounded-2xl bg-gradient-to-br ${stat.color} mb-4`}>
                <stat.icon className="w-6 h-6 text-white" />
              </div>
              <div className="text-3xl font-bold gradient-text mb-2">{stat.number}</div>
              <div className="text-sm text-gray-600 font-medium">{stat.label}</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};